{
    "name": "ConexioMarket - Core",
    "summary": "Core: registro, contratos base y cuentas",
    "author": "mhallasi",
    "category": "Integration",
    'version': '18.0.1.0.0',
    "depends": ["base", "crm", "product", "stock", "component", "base_automation"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/ir_cron.xml",
        "data/automation.xml",
        "data/mail_message_subtype.xml",
        "views/market_product_mapping_views.xml",
        "views/market_account_views.xml",
        "views/market_webhook_entry_views.xml",
        "views/market_event_queue_views.xml",
        "views/product_template_views.xml",
        "views/market_menus.xml",
    ],
    "license": "OPL-1",
    "application": False,
    'auto_install': False,
    'application': False,
}
